### ISSUE TITLE
why the embedding of '<mask>' is not zeros?

### ISSUE THREAD

**Issue by yy1252450987** [mheinzinger/SeqVec#12]
![image](https://user-images.githubusercontent.com/23442970/69343379-809c7e00-0ca8-11ea-8af4-0cc75fa10db4.png)

**Comment by mheinzinger** [comment]
There is no '< mask >' token in ELMo/SeqVec as it is auto-regressive, i.e. it does not need to mask out tokens during training (like BERT) because it is only trained on predicting the next character in a given sequence. Your '< mask >' is mapped to '< unk >' (unknown character) because it is not a valid amino acid.
